# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 667b8add198aec03849af5ac0fec3504108244d8963445d0c55d8d22343368862532ba3ecd60b5dc13e989a642a2e59b631dd965bb343d9ce8cbd01efe6e9b01

test:
  secret_key_base: 838dd3c3a75ece45271463ecc35a1746a69d7accdb4d786cab5ecf848cede0a9a2887e737ff255e64e07bf59c97317bcdd3e6a61b768be5661b89ff1786801fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
